### ISSUE TITLE
Python: Rock, Paper, Scissors

### ISSUE THREAD

**Issue by nakshatra-garg** [nakshatra-garg/hacktoberfest-coer#11]
## Description
rock paper scissors is a hand game for two or more players. Participants say “rock, paper, scissors” and then simultaneously form their hands into the shape of a rock (a fist), a piece of paper (palm facing downward), or a pair of scissors (two fingers extended). The rules are straightforward:
- Rock smashes scissors.
- Paper covers rock.
- Scissors cut paper.
<br>

Contributing Guidelines:
- The code should include comments
- There should be proper documentation (description, inputs, and outputs) contained in the README.md file.
- The file should be in the proper directory (e.g., Python/project_directory/name_of_the_file)
- The file names must be in snake case (i.e., ' ' replaced by '_')
- If you're using images in the README.md file then put them in the images folder inside your project directory.

**Comment by gakash2k01** [comment]
Do we have to make it of the options type? Like press R for rock, P for Paper and S for scissor.
Additional features: Blank Space to display current score, X to end the game, Z to restart.

I can make the commands version and if I have the option for C++, would definitely prefer it, but can work in python too. Please provide the required information and assign me the task.

**Comment by nakshatra-garg** [comment]
Yeah, You can use any approach that seems best to you. If you think assigning different buttons for different functionalities will do the job then you can use the approach.

Sure, I'll create an issue for the C++ domain.
