### ISSUE TITLE
Python: Password Generator

### ISSUE THREAD

**Issue by chiragtaneja04** [nakshatra-garg/hacktoberfest-coer#15]
## Description
A password generator is a tool that generates a random and strong password for a user. A strong password mitigates the risk of password brute-forcing. We can specify the length of the password when we generating it. A password of length 8 or more is considered to be a good password.

### Contributing Guidelines:
- The code should include comments
- There should be proper documentation (description, inputs, and outputs) contained in the README.md file.
- The file should be in the proper directory (e.g., Python/project_directory/name_of_the_file)
- The file names must be in snake case (i.e., ' ' replaced by '_')
- If you're using images in the README.md file then put them in the images folder inside your project directory.

**Comment by nakshatra-garg** [comment]
Merged #16
