### ISSUE TITLE
Python: Duplicate Remover

### ISSUE THREAD

**Issue by nakshatra-garg** [nakshatra-garg/hacktoberfest-coer#17]
## Description
Create a Python program to remove duplicates from a list. Try out multiple approaches.

### Contributing Guidelines:
- The code should include comments
- There should be proper documentation (description, inputs, and outputs) contained in the README.md file.
- The file should be in the proper directory (e.g., Python/project_directory/name_of_the_file)
- The file names must be in snake case (i.e., ' ' replaced by '_')
- If you're using images in the README.md file then put them in the images folder inside your project directory.

**Comment by Athi223** [comment]
I'd like to contribute to this, could you assign it to me?

**Comment by Athi223** [comment]
@nakshatra-garg Done, please review.
