### ISSUE TITLE
Python: Password Generator

### ISSUE THREAD

**Issue by nakshatra-garg** [nakshatra-garg/hacktoberfest-coer#69]
## Description
To create a password with Python, you need to create a program that takes the length of the password and generates a random password of the same length.

### Contributing Guidelines:
- The code should include comments
- There should be proper documentation (description, inputs, and outputs) contained in the README.md file.
- The file should be in the proper directory (e.g., Python/project_directory/name_of_the_file)
- The file names must be in snake case (i.e., ' ' replaced by '_')
- If you're using images in the README.md file then put them in the images folder inside your project directory.

**Comment by Rakshita2604** [comment]
I am currently working on the code of generation of random passwords. Please assign me this.
